version: '3'

tasks:
  test:
    desc: "Run all Go tests"
    cmds:
      - go test ./...
  build:
    desc: "Build the project"
    cmds:
      - rm -r .git
      - rm -r .github
      - git init
      - git add .
      - go run main.go build
  lint:
    desc: "Run golangci-lint"
    cmds:
      - golangci-lint run ./...